[ProjectConfig]
mode=production


# 大模型配置D
[MLLMConfig]
llm_model_name=Qwen3-VL-235B-A22B-Instruct
llm_model_url=http://aitest-beta.rnd.huawei.com/v1/chat/completions
vlm_model_name=Qwen3-VL-235B-A22B-Instruct
vlm_model_url=http://aitest-beta.rnd.huawei.com/v1/chat/completions


# 测评配置
[EvalConfig]
sliding_mode=LLM
